# Generated by Django 3.2.3 on 2021-06-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofiles',
            old_name='Channel',
            new_name='channel',
        ),
    ]
