# Generated by Django 3.2.3 on 2021-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_channel_videofiles_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
