# Generated by Django 3.2.3 on 2021-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210611_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
