# Generated by Django 3.2.3 on 2021-06-11 09:41

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_videodetail_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to=videos.models.avatar_directory_path),
        ),
    ]
