# Generated by Django 3.2.3 on 2021-06-17 19:01

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_channel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='thumbnail',
            field=models.ImageField(upload_to=videos.models.thumbnail_directory_path),
        ),
    ]
