# Generated by Django 3.2.3 on 2021-06-21 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofiles',
            name='category',
        ),
        migrations.AddField(
            model_name='videodetail',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.category'),
            preserve_default=False,
        ),
    ]
