# Generated by Django 3.2.3 on 2021-07-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_viewcount_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='videofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_detail', to='videos.videofiles'),
        ),
    ]
