# Generated by Django 3.2.3 on 2021-07-03 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0015_videodetail_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='dislike',
            field=models.ManyToManyField(related_name='video_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='like',
            field=models.ManyToManyField(related_name='video_loved', to=settings.AUTH_USER_MODEL),
        ),
    ]
