# Generated by Django 3.2.3 on 2021-07-05 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0016_auto_20210703_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subcribers',
            field=models.ManyToManyField(related_name='subcribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
