# Generated by Django 3.2.3 on 2021-07-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_channel_subcribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visibility', models.BooleanField(choices=[(False, 'private'), (True, 'public')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.channel')),
                ('video', models.ManyToManyField(related_name='video_playlist', to='videos.VideoFiles')),
            ],
        ),
    ]
