# Generated by Django 3.2.3 on 2021-07-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_videocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_video', to='videos.channel'),
        ),
    ]
