# Generated by Django 3.2.3 on 2021-07-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_channel_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=20)),
                ('report_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_channel', to='videos.channel')),
            ],
        ),
    ]
